import Link from "next/link";
import { ProjectMediaGallery } from "./project-media";
import { ArrowRight } from "lucide-react";
import { BrandMark } from "./brand-mark";
import { SiteFooter } from "./site-footer";
import { ThemeToggle } from "./theme-toggle";
import { ProjectStatusBadge } from "./project-status-badge";
import type { CaseStudy } from "@/lib/case-studies";

export function WorkflowCaseStudy({ study }: { study: CaseStudy }) {
  const story = study.workflowStory;
  if (!story) return null;
  return <main className="min-h-screen"><header className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-5 sm:px-8"><BrandMark /><nav aria-label="Case study navigation" className="flex items-center gap-4"><Link href="/work" className="text-sm">Selected work</Link><ThemeToggle /></nav></header>
    <article className="mx-auto max-w-7xl px-5 pb-20 sm:px-8">
      <header className="grid gap-8 border-b border-border py-14 lg:grid-cols-[1fr_300px] lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><ProjectStatusBadge status={study.status} /><span className="font-mono text-xs uppercase tracking-widest text-muted-foreground">{study.kicker}</span></div><h1 className="mt-7 text-5xl font-semibold tracking-tight sm:text-7xl">{study.title}</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-muted-foreground">{study.summary}</p></div><p className="border-l-2 border-primary pl-5 text-lg font-medium leading-7">{study.signal}</p></header>
      <nav aria-label={`Explore ${study.title}`} className="grid gap-3 py-7 md:grid-cols-3">{study.paths.map((path) => <a key={path.label} href={path.href} className="rounded-xl border border-border bg-card p-5 transition hover:border-primary"><span className="flex items-center justify-between font-semibold">{path.label}<ArrowRight className="size-4 text-primary" /></span><span className="mt-2 block text-sm leading-6 text-muted-foreground">{path.description}</span></a>)}</nav>
      <p className="mb-10 text-sm text-muted-foreground">The public sandbox uses fictional branding, synthetic records, and illustrated evidence. It resets on reload or after 30 minutes.</p>
      <section className="grid gap-8 border-t border-border py-10 md:grid-cols-[220px_1fr]"><h2 className="text-2xl font-semibold">The problem</h2><div><p className="max-w-3xl text-lg leading-8 text-muted-foreground">{study.problem}</p><p className="mt-4 text-sm leading-7 text-muted-foreground">Built for {study.intendedFor.charAt(0).toLowerCase() + study.intendedFor.slice(1)}</p></div></section>
      <section className="grid gap-8 border-t border-border py-10 md:grid-cols-[220px_1fr]"><h2 className="text-2xl font-semibold">The observation</h2><p className="max-w-3xl text-lg leading-8 text-muted-foreground">{story.observation}</p></section>
      <section className="border-y border-border py-10"><div className="font-mono text-xs uppercase tracking-widest text-primary">The workflow</div><h2 className="mt-3 text-3xl font-semibold tracking-tight">Carry the context forward.</h2><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{story.handoffs.map((handoff, index) => <article key={handoff.role} className="rounded-xl border border-border bg-card p-5"><div className="font-mono text-xs text-primary">0{index + 1}</div><h3 className="mt-3 font-semibold">{handoff.role}</h3><p className="mt-5 text-xs font-semibold uppercase text-muted-foreground">Before</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{handoff.before}</p><p className="mt-5 text-xs font-semibold uppercase text-primary">{study.status === "Concept prototype" ? "Proposed handoff" : "After"}</p><p className="mt-2 text-sm leading-6">{handoff.after}</p></article>)}</div></section>
      <section className="grid gap-8 py-10 md:grid-cols-[220px_1fr]"><h2 className="text-2xl font-semibold">The solution</h2><div><p className="max-w-3xl text-lg leading-8 text-muted-foreground">{study.solution}</p><ul className="mt-6 grid gap-3 text-sm sm:grid-cols-2">{study.capabilities.map((capability) => <li key={capability} className="rounded-lg border border-border p-3">{capability}</li>)}</ul></div></section>
      <section aria-labelledby="scenario-heading" className="border-t border-border py-10"><h2 id="scenario-heading" className="text-3xl font-semibold tracking-tight">The happy path is only the beginning.</h2><p className="mt-3 max-w-3xl text-muted-foreground">{story.scenarios.length} deliberate scenarios show where a handoff succeeds, where it stops, and what the next person needs.</p><div className="mt-7 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{story.scenarios.map((scenario) => <a key={scenario.id} href={`${story.demoUrl ?? "https://ops.yorkstead.com/rework"}?mode=guided&scenario=${scenario.id}`} className="rounded-xl border border-border bg-card p-5 transition hover:border-primary"><h3 className="font-semibold">{scenario.title} <span aria-hidden="true">↗</span></h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{scenario.description}</p></a>)}</div></section>
      <section className="grid gap-8 border-t border-border py-10 md:grid-cols-[220px_1fr]"><h2 className="text-2xl font-semibold">Intended outcomes</h2><div><p className="max-w-3xl text-lg leading-8 text-muted-foreground">{study.outcome}</p><p className="mt-5 border-l-2 border-border pl-5 text-sm leading-7 text-muted-foreground">{study.limitations}</p></div></section>
      <section id="architecture" className="scroll-mt-8 border-t border-border py-10"><div className="font-mono text-xs uppercase tracking-widest text-primary">Architecture</div><h2 className="mt-3 text-3xl font-semibold tracking-tight">A public demo with its own boundary.</h2><div className="mt-7 grid gap-5 md:grid-cols-2">{story.architecture.map((part) => <div key={part.title} className="rounded-xl border border-border p-5"><h3 className="font-semibold">{part.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{part.description}</p></div>)}</div></section>
      <section className="mt-6 rounded-xl border border-border bg-card p-8"><h2 className="text-2xl font-semibold">Where does your team have to reconstruct the work?</h2><p className="mt-3 max-w-2xl text-muted-foreground">Start with one handoff: the information arriving, the decision being made, and what the next person needs.</p><Link href={study.cta.href} className="mt-6 inline-flex min-h-11 items-center gap-3 rounded-lg bg-primary px-5 py-3 font-medium text-primary-foreground">{study.cta.label}<ArrowRight className="size-4" /></Link></section>
      {study.media.length > 0 && <section className="border-t border-border py-10"><h2 className="mb-6 text-2xl font-semibold">Prototype interface</h2><p className="mb-6 text-muted-foreground">Screens from the broader concept application. The public walkthrough above is a focused, fictional simulation.</p><ProjectMediaGallery media={study.media} projectTitle={study.title} /></section>}
    </article><SiteFooter /></main>;
}
