import type { CaseStudy } from "./case-studies";

export const reworkCaseStudy: CaseStudy = {
  slug: "rework-flow", number: "06", status: "In development", title: "Rework Flow",
  kicker: "Flagship workflow case study · Confirmed $7,500 System", icon: "layers",
  summary: "A freight exception should not become an office mystery. Rework Flow connects the arrival promise, dock work, evidence, and invoice through one load record.",
  signal: "The next person receives the work and the reason behind it.",
  industries: ["Cross-docking", "Freight rework", "Warehousing", "Exception handling"],
  intendedFor: "Dispatchers, dock operators, and office teams whose work crosses physical and administrative handoffs.",
  problem: "A shifted load arrives with urgency. Dispatch needs capacity, the dock needs an accurate scope, and billing needs proof of what happened. When each role keeps its own notes, the office must reconstruct the job after the driver leaves.",
  previousWorkflow: "Phone request → separate bay note → material tally → disconnected photos → signature chase → manually reconstructed invoice.",
  solution: "Keep the reservation, actual material counts, before-and-after evidence, driver acknowledgment, and calculated charges on a single job. Make unresolved handoffs visible before billing.",
  capabilities: ["Timed bay reservation", "Actual material and labor counts", "Before-and-after evidence", "Driver sign-off checkpoint", "Itemized demo invoice", "Resettable exception scenarios"],
  technologies: ["Next.js", "TypeScript", "Offline-tolerant dock terminal", "Live office board"],
  outcomeLabel: "Intended outcome",
  outcome: "Intended outcomes are a clearer arrival promise, visible differences between requested and actual work, and a billing handoff that carries its supporting record. The application is built around these behaviors; time saved, dispute reduction, revenue recovery, and customer acceptance have not been measured.",
  limitations: "The walkthrough shows screens from the working application with a made-up company name, example people and loads, and illustrative photos. The software is a prototype still in development and is not yet running in a live operation. Available as a purchased system for $7,500. Included configuration, implementation, integrations, and handoff are defined in the proposal. Continued use of the purchased system does not require a Yorkstead support subscription. Hosting and third-party services are identified separately. Account ownership, billing, and ongoing responsibilities are agreed before implementation.",
  applications: [
    { title: "Dispatch to dock", description: "Carry the arrival promise and expected scope into the operator's job." },
    { title: "Dock to office", description: "Deliver counts, condition evidence, and sign-off with the completed work." },
    { title: "Exception review", description: "Expose expired holds, count differences, damage, and missing sign-off before the next handoff." },
  ],
  paths: [
    { label: "Walkthrough", description: "Follow a job from reservation to a signed completion packet, screen by screen.", href: "/demos/rework" },
    { label: "Architecture", description: "See the workflow model and public-demo boundary.", href: "/work/rework-flow#architecture" },
  ],
  media: [
    {
      id: "rework-dispatch-board",
      type: "screenshot",
      label: "Live operations and dispatch board",
      description: "The prototype Rework Flow live operations board showing active bay occupancy, rework billing metrics, driver call intake, and real-time dispatch log records.",
      caption: "The central office board connects driver intake, bay reservation capacity, rework logging, and billing status in one unified ledger.",
      alt: "ReworkFlow prototype operations board and dispatch log",
      desktop: { src: "/media/rework-flow/dispatch-board.png", width: 1024, height: 582 },
      expandable: true,
      featured: true,
    },
  ],
  previewMediaId: "rework-dispatch-board",
  cta: { label: "Inquire about Rework Flow", href: "/?product=rework-flow#contact" },
  workflowStory: {
    observation: "The useful unit is the load, not the screen. The inspected implementation already connected bay reservations, material counts, condition evidence, and billing. The walkthrough follows those connections from a driver's reservation to a signed completion packet.",
    handoffs: [
      { role: "Driver → Dispatch", before: "A phone promise with a separate bay note.", after: "A timed reservation carrying requested work and arrival context." },
      { role: "Dispatch → Dock", before: "The operator reconstructs the request at the trailer.", after: "One job shows the requested quantity alongside the actual tally." },
      { role: "Dock → Office", before: "Photos, counts, and signatures need to be collected again.", after: "Evidence and sign-off travel with the completed handoff." },
      { role: "Office → Invoice", before: "Charges are typed from scattered notes.", after: "Itemized charges derive from the same material and labor record." },
    ],
    scenarios: [
      { id: "reserve", title: "Reserve a bay", description: "A driver gets a fixed price range and a bay before arriving.", href: "/demos/rework#reserve" },
      { id: "intake", title: "Dock intake", description: "The operator confirms trailer, carrier, driver and bay.", href: "/demos/rework#intake" },
      { id: "before", title: "Before photos", description: "Record the condition the freight arrived in.", href: "/demos/rework#before" },
      { id: "tally", title: "Supplies and labor", description: "Count materials and time while the invoice updates.", href: "/demos/rework#tally" },
      { id: "sign", title: "Driver sign-off", description: "An after photo and a signature on the glass.", href: "/demos/rework#sign" },
      { id: "certificate", title: "Completion packet", description: "Photos, itemized invoice and signature in one record.", href: "/demos/rework#certificate" },
    ],
    architecture: [
      { title: "A working application", description: "Rework Flow is a Next.js application with a driver reservation page, a dock terminal for phones and tablets, and an office board that updates as the dock works." },
      { title: "Real screens, example data", description: "The walkthrough uses screens captured from the running application with a made-up company name, example carriers and illustrative photos. Nothing on the page is connected to a customer system." },
      { title: "Evidence travels with the job", description: "Photos, counts, the driver's signature and an append-only audit record stay attached to one load, so the office bills from the same record the dock created." },
      { title: "Still in development", description: "Dispute rate and turnaround figures in the demo are placeholders. No measured business outcomes are claimed." },
    ],
  },
};
